name: Build Nubia NX616J (LineageOS 22.2)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "nubia_nx616j"
  DEVICE_CODENAME : "nx616j"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld"

  KERNEL_SOURCE : "https://github.com/LineageOS/android_kernel_nubia_sdm845"
  KERNEL_BRANCH : "lineage-22.2"

  CLANG_SOURCE : "https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git"
  CLANG_BRANCH : "lineage-20.0"

  GCC_GNU : false
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android12L-release"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "android12L-release"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/nubia/sdm845_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "resukisu"

  SUSFS_ENABLE : true
  SUSFS_FIXED : true
  SUSFS_UPDATE : true

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "lineageos_22.2"

  # Other env
  PYTHON_VERSION: "3"

  PACK_METHOD: "Anykernel3"

  KERNELSU_METHOD: "shell"
  KERNELSU_SUS_PATCH: "false"

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches"
  PATCHES_BRANCH: "mi_kernel"

  SUSFS_FOLDER_FIXED: ""
  SUSFS_PATCH_FIXED: ""

  REKERNEL_ENABLE: "true"

  HOOK_METHOD: "syscall"
  HOOK_OLDER: "false"

  KERNEL_PATCH: "false"

  KPM_ENABLE: "true"
  KPM_INLINE: "true"
  KPM_KPATCH_NEXT: "false"
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux"

  BASEBAND_GUARD_ENABLE: "true"
  BASEBAND_GUARD_BOOT: "false"

  HIDE_STUFF: "true"

  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"

  BUILD_DEBUGGER: "true"
  SKIP_PATCH: "true"

  BUILD_OTHER_CONFIG: "true"
  MERGE_CONFIG_FILES: "vendor/nubia/nx616j.config"

  FREE_MORE_SPACE: "false"

jobs:
  build-kernel:
    name: Nubia NX616J (LineageOS 22.2)
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get necessary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🔧 Patch Hide Stuff
        uses: ./.github/workflows/patch-hide-stuff

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
        
